#!/bin/bash

# Get the current date and time
DATE=$(date '+%Y-%m-%d %H:%M:%S')

# Get the current username
USERNAME=$(whoami)

# Print header
echo -e "\nSystem Report generated by $USERNAME, $DATE\n"

# Get system information
HOSTNAME=$(hostname)
source /etc/os-release  # This file contains OS distribution information
UPTIME=$(uptime -p)    # Get uptime in a human-readable format

# Print System Information
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $NAME $VERSION"
echo "Uptime: $UPTIME"

# Get hardware information
CPU=$(lshw -short -C cpu | grep -i "processor" | awk '{$1=""; print $0}')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISKS=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "sr0" | awk '{print $3 " " $2}')
VIDEO=$(lshw -short -C display | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')

# Print hardware information
echo -e "\nHardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s): $DISKS"
echo "Video: $VIDEO"

# Get network information
FQDN=$(hostname -f)  # Fully Qualified Domain Name
HOST_IP=$(ip a show eth0 | grep inet | awk '{print $2}' | cut -d/ -f1)  # Adjust interface name if necessary
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

# Print network information
echo -e "\nNetwork Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"

# Get system status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
DISK_SPACE=$(df -h | grep -E '^/dev/' | awk '{print $1 " " $4 " available"}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | grep -v "Address" | tr '\n' ',' | sed 's/,$//')
UFW_STATUS=$(sudo ufw status | grep -i "status" | awk '{print $2}')

# Print system status
echo -e "\nSystem Status"
echo "-------------"
echo "Users Logged In: $LOGGED_IN_USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
